### ISSUE TITLE
Projectile-run-cmd-map support?

### ISSUE THREAD

**Issue by litlpoet** [LefterisJP/malinka#6]
Hi LefterisJP.

I really like the way you manage c++ projects. Most of the packages that I've used for c++ developments (`rtags`, `irony`, `flycheck`) are now tightly connected by `malinka`. Defining a project is really straightforward and until now it works like a charm. Especially, pushing several commands automatically to `projectile` is great. I don't need `.dir-locals.el` anymore.

One missing set-up regarding `projectile` is a command for running an application. (bounded to `C-c p u` in `projectile`). I guess it can be implemented via `projectile-run-cmd-map`. Could you please add this feature?

**Comment by LefterisJP** [comment]
There you go.

Just add an additional `run-cmd` key-value argument to `malinka-define-project like so:

```elisp
(malinka-define-project
 :name "refuclib"
 :root-directory "/home/lefteris/w/refu/clib"
 :build-directory "/home/lefteris/w/refu/"
 :configure-cmd "scons -c clib_tests && scons clib_tests"
 :compile-cmd "scons  clib"
 :test-cmd "scons clib_tests"
 :run-cmd "./check_exec")
```

**Comment by litlpoet** [comment]
Thank you so much! It's real quick:)
