### ISSUE TITLE
Problem with flycheck

### ISSUE THREAD

**Issue by dvzubarev** [LefterisJP/malinka#9]
I use spacemacs 0.104 based on emacs 24.4
cmake 2.8.12
I can configure my project and use rtags.
But flycheck is not set up properly since flycheck-clang-include-path is nil.
Moreover it seems there is no information stored about configured files, because when
i print fileattr variable from https://github.com/LefterisJP/malinka/blob/master/malinka.el#L1222
i get always 'not-configured.
The value of my malinka--projects-map,

  #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data
              ("doc_x"
               [cl-struct-malinka--project "doc_x" "/xxx/" "/xxx/build/" "cmake ../ -DCMAKE_INCLUDE_PATH=/compiled/include -DCMAKE_CXX_FLAGS=\"--std=c++0x\"" "cd /xxx/build/ && make -j4 install" nil nil nil]))

**Comment by LefterisJP** [comment]
Hello,

Do you configure your project with malinka feeding the data to rtags, or do you do it manually? And can you use rtags succesfully?

**Comment by dvzubarev** [comment]
I invoke malinka-project-configure,
then i have following in my Messages

Malinka-info: Configuring project doc_terms
Malinka-debug: Project's root dir is /home/denin/Programms/CXXWorksapce/TextApp/modules/cgi-doc-terms/
Malinka-debug: We got cmake version 2.8.12
Malinka-info: Executing cmake command: "cd /home/denin/Programms/CXXWorksapce/TextApp/modules/cgi-doc-terms/build/ && cmake ../ -DCMAKE_INCLUDE_PATH=/compiled/include -DCMAKE_LIBRARY_PATH=/compiled/lib -DCMAKE_INSTALL_PREFIX=/compiled -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--std=c++0x" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
Malinka-info: Waiting for cmake to finish
Malinka-info: Cmake command for "doc_terms" finished. Proceeding to process the output
Malinka-info: Feeding compile database file: "/home/denin/Programms/CXXWorksapce/TextApp/modules/cgi-doc-terms/build/compile_commands.json" to RTAGS

Then  I can use rtags succesfully

**Comment by LefterisJP** [comment]
I think the flycheck issue should be fixed now. If not please reopen the issue.
